### ISSUE TITLE
Regarding 03_lights_model 

### ISSUE THREAD

**Issue by mnitin59** [thinkingmachines/ph-poverty-mapping#17]
Can you let me know for the ntl_summary_stats_file is same file name ph_ntl_ntl_points.csv or another file which is not uploaded in the git. 

I got confused with the code on 

# Define feature columns
feature_cols = ['cov', 'kurtosis', 'max', 'mean', 'median', 'min', 'skewness', 'std']

because in the Correlations section code 
I'm getting an error -> " KeyError: 'cov' "

**Comment by ibtingzon** [comment]
@mnitin59 Added `nightlights_summary_stats.csv` [here](https://github.com/thinkingmachines/ph-poverty-mapping/blob/master/data/nightlights_summary_stats.csv) in #18.
