### ISSUE TITLE
00_dhs_prep.ipynb Code error 

### ISSUE THREAD

**Issue by GIS243** [thinkingmachines/ph-poverty-mapping#35]
Hi @ardieorden ardieorden

For the following notebook **00_dhs_prep.ipynb**
data = dhs[[
    'Cluster number',
    'Wealth index factor score combined (5 decimals)',
    'Education completed in single years',
    'Has electricity'
]].groupby('Cluster number').mean()

data['Time to get to water source (minutes)'] = dhs[[
    'Cluster number',
    'Time to get to water source (minutes)'
]].replace(996, 0).groupby('Cluster number').median()

**data.columns = [[
    'Wealth Index',
    'Education completed (years)',
    'Access to electricity',
    'Access to water (minutes)'
]]**

print('Data Dimensions: {}'.format(data.shape))
data.head(2)

For the bold part, I am getting the error message, how to resolve this, please. 
![image](https://user-images.githubusercontent.com/54910955/107861540-6c482200-6e14-11eb-9edb-91e07acaa36c.png)
 

Thanks

**Comment by ardieorden** [comment]
Hi @GIS243 , we'll try reproducing this error by this week and we'll get back to you then!

**Comment by GIS243** [comment]
@ardieorden 

I implemented it on Jupyter Notebook and it worked. 

Thanks

**Comment by ardieorden** [comment]
Hi @GIS243 , got caught up in other work, sorry!

Glad to know it worked! I'll close this issue now.
