### ISSUE TITLE
dhs csv data

### ISSUE THREAD

**Issue by iokanyalcin** [thinkingmachines/ph-poverty-mapping#36]
In the first notebook, I saw that you have changed many of the duplicated data of Time to get to water source minutes from 996 to 0. May I ask that what was the reason for this change? 

Thanks from now.

**Comment by ardieorden** [comment]
Hi @iokanyalcin !

If you check page 98 of the Guide to DHS Statistics (https://dhsprogram.com/pubs/pdf/DHSG1/Guide_to_DHS_Statistics_DHS-7.pdf), you'll see that 996 is code for water on premises. Since this is the case, the respondent is 0 minutes away from the water source.

**Comment by iokanyalcin** [comment]
Thank you!
