### ISSUE TITLE
Hardware and Software Requirements

### ISSUE THREAD

**Issue by GIS243** [thinkingmachines/ph-poverty-mapping#37]
Hi, @ardieorden 

Can you please mention the hardware and software requirements to run this project? 

Thanks

**Comment by ardieorden** [comment]
Hi @GIS243 !

For model training, we had the following hardware requirements: 16 vCPUs and 60 GB of memory (n1-standard-16) and an NVIDIA Tesla P100 GPU.

For non-model training, the hardware requirements can probably be brought down to 4 vCPUs and 16GB of memory and no GPU.

The software requirements can be seen in [`requirements.txt`](https://github.com/thinkingmachines/ph-poverty-mapping/blob/master/requirements.txt).

**Comment by GIS243** [comment]
@ardieorden Thanks 

You can close this issue
