### ISSUE TITLE
Best Model 

### ISSUE THREAD

**Issue by GIS243** [thinkingmachines/ph-poverty-mapping#38]
Hi @ardieorden        

While running the 03_transfer_model notebook. 

I am getting the following error message. How to select the Best_model.pt, Do we have to do this manually or code will do this for us. 

![image](https://user-images.githubusercontent.com/54910955/110151481-8ab79280-7dae-11eb-91c6-926572dc9460.png)

**Comment by ibtingzon** [comment]
@GIS243 `model_best.pt` is generated after you run `src/train.py` - the code should automatically do this for you.

**Comment by jtmiclat** [comment]
Hi! Closing this issue as ill be archiving this repository. To see our new poverty mapping project checkout https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping
