### ISSUE TITLE
Add instructions and scripts for downloading and pre-processing DHS dataset

### ISSUE THREAD

**Issue by ardieorden** [thinkingmachines/ph-poverty-mapping#6]
The DHS dataset for the Philippines can be found in this [link](https://dhsprogram.com/What-We-Do/survey-search.cfm?pgtype=main&SrvyTp=country).

**Comment by ardieorden** [comment]
Closing this stale issue.

**Comment by ardieorden** [comment]
@ibtingzon Placing @kevinthomasgo 's notebook for pre-processing the DHS dataset here:

https://gist.github.com/ardieorden/bc8a70d7479705abe2debe6115e924a9

**Comment by ibtingzon** [comment]
@ardieorden oh, yikes, the notebook reveals some of the data from DHS dataset (this might be in violation of the DHS ToS). Let's remove it for the meantime, and I'll upload a "clean" script for DHS pre-processing in the coming week.

**Comment by ardieorden** [comment]
@ibtingzon Thanks for the catch! Alright, got it

**Comment by ljvmiranda921** [comment]
:warning: :warning: :warning:
If that's the case then we might need to purge the files even after you upload a "clean" script. The previous versions can still be found in the git history.
