### ISSUE TITLE
Add nighttime lights data, feature embeddings (csv format) to data directory

### ISSUE THREAD

**Issue by ibtingzon** [thinkingmachines/ph-poverty-mapping#7]
- [x] Add extracted feature embeddings in CSV format to data directory
- [x] Add nighttime lights data  in CSV format to data directory

**Comment by ardieorden** [comment]
@issa-tingzon The nighttime lights data are [uploaded to BQ](https://console.cloud.google.com/bigquery?project=tm-geospatial&folder&organizationId=301224238109&p=tm-geospatial&d=ntl_grid&t=ntl&page=table) which might help in closing up this issue.

**Comment by mnitin59** [comment]
Can you please share the CSV File through the drive as the link you have given doesn't have any dataset in that file.

**Comment by ardieorden** [comment]
Hi @mnitin59 , here's the link to the CSV file for the nighttime lights data:

https://drive.google.com/file/d/1aQdTEF8G1WsBYbA6iDkPvvZj8gWHIduh/view?usp=sharing

**Comment by mnitin59** [comment]
Thank you for the file. 

Actually, I'm looking for the Survey Model process and interested to know which data is used for implementing the model. As I can see the data merged in between for correlation process.  
Can you give help on guiding and giving access to the Google Cloud Storage Section code for dhs_features.csv, dhs_indicators.csv, osm_roads.csv, osm_buildings.csv files for Clustering Data Analysis? 
I would be happy to work on this project and explore new things if possible.

**Comment by ardieorden** [comment]
Hi @mnitin59 ,

I can give access to the datasets that you mentioned. Here they are.

dhs_features.csv: https://drive.google.com/file/d/10cAd4YTruD3MTLS53jPnDFWyjB5h1JxV/view?usp=sharing

dhs_indicators.csv: https://drive.google.com/file/d/11PdQLciZiIzg0ahJR_e-Mifdnut0hpLk/view?usp=sharing

osm_roads.csv: https://drive.google.com/file/d/1UsQ_c5lXuCwUzZCaj1wBi0UAoszl6p8C/view?usp=sharing

osm_buildings.csv: https://drive.google.com/file/d/1GUqAyzAOGkutDmcO8VxSNKQxW581qdMD/view?usp=sharing

With regards to guiding you through the clustering and data analysis, my colleague @issa-tingzon might be able to explain the process better.

**Comment by ardieorden** [comment]
@ibtingzon @issa-tingzon You can just make a PR to include the notebook which demonstrates the DHS preprocessing and clustering methodology

**Comment by mnitin59** [comment]
@ardieorden  Thank you for the information. Actually, I have created an account and requested for DHS Datasets many times but DHS Website has not approved my project proposal. 
Can you guide on any alternative options?

**Comment by mnitin59** [comment]
@ardieorden I have checked with the survey model and would like to process all models. 
I would be trying to plot the geopanda mapping on the model which can show the prediction scale with the color format. Can you provide data resources for the following files? 
 nightlights.csv, nightlights_unstacked.csv, nightlights_bins.csv, nightlights_train.csv, nightlights_train_bal.csv, nightlights_val.csv, report.csv, nightlights_summary_stats.csv, model.pt, Test images for sanity checking purposes, osm_pois.csv. 
dhs_provinces.csv, dhs_regions.csv (Links)

I would be thankful for your guidance and resources help.

**Comment by ibtingzon** [comment]
@mnitin59  
Nightlights dataset [can be found here](https://github.com/thinkingmachines/ph-poverty-mapping/blob/master/data/nightlights.csv).
You can generate `nightlights_unstacked.csv`, `nightlights_bins.csv`, `nightlights_train.csv`, `nightlights_train_bal.csv`, and `nightlights_val.csv` by running [02_lights_eda.ipynb](https://github.com/thinkingmachines/ph-poverty-mapping/blob/master/notebooks/02_lights_eda.ipynb). 
`model.pt` can be generated by running [transfer_learning_script.py](https://github.com/thinkingmachines/ph-poverty-mapping/blob/master/src/transfer_learning_script.py). 
Test images are in [this folder](https://github.com/thinkingmachines/ph-poverty-mapping/tree/master/data/test_images).

**Comment by mnitin59** [comment]
@ibtingzon Thank you very much! :)
